server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
      - id: student-service
        uri: http://localhost:8081/
        predicates:
        - Path=/student/**
      - id: teacher-service
        uri: http://localhost:8082/
        predicates:
        - Path=/teacher/**
      - id: course-service
        uri: http://localhost:8083/
        predicates:
        - Path=/course/**
      - id: relative-service
        uri: http://localhost:8084/
        predicates:
        - Path=/relative/**
