eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8084
spring:
  data:
    mongodb:
      database: RelativeDB
      host: localhost
      port: 27017
